### ISSUE TITLE
Block height and stratum

### ISSUE THREAD

**Issue by alfredalappat** [HugoXOX3/PythonBitcoinMiner#9]
If a new block appears then it is  restarting,but the block height remains the same . Is it also cause any problems for new block template? Like not changing the attributes like timestamp, merkleroot,etcc..?. If so please improve or update this code. Or else even if I get a solution in anytime in my life that will not be useful........... thank you for the code and explanation. Also a simple doubt. Is the stratum protocol is needed in the code? or not? Is it cause any trouble while sending the payload?.

**Comment by HugoXOX3** [comment]
All Bug are fixed at [Beta Version v2.0.0](https://github.com/HugoXOX3/PythonBitcoinMiner/releases/tag/Minerv2.0.0)
